Multithreading
Pavel-Laukhin/Analog-of-Instagram pull request #1
Opened 2020-10-05 06:53 UTC by Pavel-Laukhin

Я сделяль!

2020-10-13 04:08 UTC, nskazakov requested changes
- [ ] Исправить утечки памяти

2020-10-13 04:08 UTC, nskazakov commented on Course2FinalTask/Code/AddNew/Filter/FilterImageOperation.swift
> +    private var _inputImage: UIImage?
в свифте можно не писать так: `_inputImage`. Можно без нижнего подчеркивания. В обж-си такое делалось для того, чтобы не было коллизии имен. У нас это все проще и если ты в ините обратишься по self, что ты и делаешь, то он именно твою переменную и будет иметь в виду

2020-10-13 04:08 UTC, nskazakov commented on Course2FinalTask/Code/AddNew/Filter/FilterImageOperation.swift
> +        guard let coreImage = CIImage(image: _inputImage!) else { return }
Force unwrap плохо. Ты же можешь до создания coreImage развернуть опционал
```
guard let inputImage = _inputImage, 
let coreImage = CIImage(image: inputImage) else { return }
```

2020-10-13 04:08 UTC, nskazakov commented on Course2FinalTask/Code/AddNew/Filter/FilterImageOperation.swift
> +        guard let filter = CIFilter(name: _chosenFilter!) else { return }
та же ситуация, как выше

2020-10-13 04:08 UTC, nskazakov commented on Course2FinalTask/Code/AddNew/Filter/FilterViewController.swift
> +            operation.completionBlock = {
тут забыл пофиксить утечку памяти

2020-10-13 04:08 UTC, nskazakov commented on Course2FinalTask/Code/AddNew/Filter/FilterViewController.swift
> +            operation.completionBlock = {
```operation.completionBlock = { [weak self] in```

2020-10-13 04:08 UTC, nskazakov commented on Course2FinalTask/Code/AddNew/Filter/FilterViewController.swift
> +        operation.completionBlock = {
ситуация аналогична предыдущей

2020-10-13 04:08 UTC, nskazakov commented on Course2FinalTask/Code/AddNew/Filter/FilterViewController.swift
> +        operation.completionBlock = {
у тебя поэтому и держится imageView

2020-10-13 04:08 UTC, nskazakov commented on Course2FinalTask/Code/AddNew/Filter/FilterViewCell.swift
> +        imageView.image = nil
это можно делать в методе prepareForReuse

2020-10-13 04:08 UTC, nskazakov commented on Course2FinalTask/Code/AddNew/Share/ShareViewController.swift
> +            ].forEach { view.addSubview($0)}
странный перенос строк

2020-10-13 04:08 UTC, nskazakov commented on Course2FinalTask/Code/AddNew/Share/ShareViewController.swift
> +        DataProviders.shared.postsDataProvider.newPost(with: image, description: textView.text, queue: queue) { post in
здесь тоже будет утечка памяти, тк ты в алерт передаешь self

2020-10-13 04:08 UTC, nskazakov commented on Course2FinalTask/Code/Feed/FeedViewController+DelegateFlowLayout.swift
> +//    }
можно и вовсе удалить

2020-10-13 04:08 UTC, nskazakov commented on Course2FinalTask/Code/Feed/FeedViewController.swift
> +                guard let user = user else {
можно в один guard объединить

2020-10-13 04:08 UTC, nskazakov commented on Course2FinalTask/Code/TabBar/TabBarController.swift
> +        DataProviders.shared.usersDataProvider.currentUser(queue: queue) { user in
утечка памяти снова

2020-10-18 11:43 UTC, Pavel-Laukhin commented on Course2FinalTask/Code/AddNew/Filter/FilterImageOperation.swift
> +    private var _inputImage: UIImage?
Спасибо, исправил!

2020-10-18 11:45 UTC, Pavel-Laukhin commented on Course2FinalTask/Code/AddNew/Filter/FilterImageOperation.swift
> +        guard let coreImage = CIImage(image: _inputImage!) else { return }
Понял, спасибо, исправил!
Ошибка была, потому что бездумно скопировал из кода Легиона. В следующий раз буду смотреть внимательнее :)

2020-10-18 11:46 UTC, Pavel-Laukhin commented on Course2FinalTask/Code/AddNew/Filter/FilterImageOperation.swift
> +        guard let filter = CIFilter(name: _chosenFilter!) else { return }
Исправлено!

2020-10-18 11:48 UTC, Pavel-Laukhin commented on Course2FinalTask/Code/AddNew/Filter/FilterViewController.swift
> +            operation.completionBlock = {
Исправил!

2020-10-18 11:48 UTC, Pavel-Laukhin commented on Course2FinalTask/Code/AddNew/Filter/FilterViewController.swift
> +        operation.completionBlock = {
Ага, понял, спасибо, исправил!

2020-10-18 11:49 UTC, Pavel-Laukhin commented on Course2FinalTask/Code/AddNew/Share/ShareViewController.swift
> +            ].forEach { view.addSubview($0)}
Я бы рад сделать иначе, но не знаю, как правильно :(

2020-10-18 12:21 UTC, Pavel-Laukhin commented on Course2FinalTask/Code/AddNew/Share/ShareViewController.swift
> +        DataProviders.shared.postsDataProvider.newPost(with: image, description: textView.text, queue: queue) { post in
готово!

2020-10-18 12:21 UTC, Pavel-Laukhin commented on Course2FinalTask/Code/Feed/FeedViewController+DelegateFlowLayout.swift
> +//    }
удалил!

2020-10-18 12:39 UTC, Pavel-Laukhin commented on Course2FinalTask/Code/Feed/FeedViewController.swift
> +                guard let user = user else {
готово!

2020-10-18 12:43 UTC, Pavel-Laukhin commented on Course2FinalTask/Code/TabBar/TabBarController.swift
> +        DataProviders.shared.usersDataProvider.currentUser(queue: queue) { user in
готово!

2020-10-19 12:20 UTC, nskazakov approved these changes

2020-11-30 14:50 UTC, merged